POST  http://localhost:3003/turma
Content-Type: application/json

{

    "nome":"PABLITO",
    "modulo":5
}

###
PUT http://localhost:3003/turma/1656011964827
Content-Type: application/json

{
    "modulo":10
}

###########

GET http://localhost:3003/turma
Content-Type: application/json

#############################

POST  http://localhost:3003/estudante
Content-Type: application/json

{
        "nome": "Servin",
        "email": "servulin@gmail.com",
        "data_nasc": "1978/09/26",
        "turma_id": "01",
        "hobbies": "Taca pedra em ônibus"
}

#############################

GET http://localhost:3003/estudante

############################


PUT http://localhost:3003/estudante/01
content-type: application/json

{
      "turma_id":"1656011964827"
}


##########################

POST http://localhost:3003/docente
content-type: application/json

{
        "nome": "Vitor Hugo",
        "email": "vitor@gmail.com",
        "data_nasc": "1978/09/26",
        "turma_id": "01",
        "especialidades": "Machine Learning"
}

###########################

GET http://localhost:3003/docente



#################

PUT http://localhost:3003/docente/01
Content-Type: application/json

{
    "turma_id": "1656011964827"
}
