POST  http://localhost:3003/turma
Content-Type: application/json

{

    "nome":"PABLITO",
    "modulo":5
}

###


GET http://localhost:3003/turma
Content-Type: application/json

#############################

POST  http://localhost:3003/estudante
Content-Type: application/json

{

        "nome": "Servin",
        "email": "servulin@gmail.com",
        "data_nasc": "1978/09/26",
        "turma_id": "01",
        "hobbies": "Taca pedra em ônibus"

}
